server:
  port: 9000
spring:
  profiles:
    active: dev


pageSize: 2
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hourglass
  cloud.stream:
    bindings:
      output-goals:
        destination: goals
    kafka.binder:
      brokers: 127.0.0.1
      defaultBrokerPort: 9092
---
spring:
  profile: prod
  data:
    mongodb:
      host: localhost
      port: 27018
      database: hourglass
  cloud.stream:
    bindings:
      output-goals:
        destination: goals
    kafka.binder:
      brokers: 127.0.0.1
      defaultBrokerPort: 9092
