server:
  port: 9000
spring:
  profiles:
    active: dev


pageSize: 5
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hourglass
  cloud.stream:
    bindings:
      output-goals:
        destination: goals
    defaultBinder: rabbit
    default.contentType: application/json

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

---
spring:
  profile: prod
  data:
    mongodb:
      host: hourglassdb-service
      port: 27017
      database: hourglass
  cloud.stream:
    bindings:
      output-goals:
        destination: goals
    kafka.binder:
      brokers: kafka
      defaultBrokerPort: 9093
spring.rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
